document.addEventListener('DOMContentLoaded',()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  $$('[data-state-option]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-state-option]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');SRP.set({outcome:btn.dataset.stateOption});SRP.toast('decision_outcome = '+btn.dataset.stateOption)}));
  $$('[data-endorse]').forEach(btn=>btn.addEventListener('click',()=>{if(SRP.get().outcome!=='reportable'){SRP.toast(SRP.txt('Only reportable can unlock this route.','只有 reportable 才能解锁本路线。'));return}SRP.set({endorsement:'endorsed'});SRP.audit('ReportabilityDecision DEC-001 endorsed','ReportabilityDecision DEC-001 已背书','Ada Rossi')}));
  $$('[data-ack-gap]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.ackGap;SRP.set(id==='utc'?{utcAck:true}:{itAck:true});SRP.toast(SRP.txt('Known gap acknowledged and retained.','已确认已知缺口并保留。'))}));
  $$('[data-prepare-package]').forEach(btn=>btn.addEventListener('click',()=>{if(!SRP.ok('endorsement')){SRP.toast(SRP.txt('Reviewer endorsement required first.','需要先完成审核背书。'));return}SRP.set({packagePrepared:true});SRP.audit('Sealed reporting package prepared','已准备封存报送包','L. Martin')}));
  $$('[data-generate-snapshot]').forEach(btn=>btn.addEventListener('click',()=>{if(!SRP.ok('package')){SRP.toast(SRP.txt('Prepare the package on P02 first.','先在 P02 准备报送包。'));return}SRP.set({snapshot:true});SRP.audit('submitted_payload_snapshot sealed','submitted_payload_snapshot 已封存','system')}));
  $$('[data-attach-receipt]').forEach(btn=>btn.addEventListener('click',()=>{if(!SRP.ok('snapshot')){SRP.toast(SRP.txt('Generate immutable snapshot first.','先生成不可变快照。'));return}SRP.set({receipt:true});SRP.audit('PortalReceiptEvidence attached: received_registered','PortalReceiptEvidence 已附加：received_registered','J. Novak')}));
  $$('[data-row-id]').forEach(row=>row.addEventListener('click',()=>{$$('[data-row-id]').forEach(r=>r.classList.remove('selected'));row.classList.add('selected');const id=row.dataset.rowId;const panel=$('[data-workbench-detail]');if(panel)panel.innerHTML=`<div class="panel-label">SELECTED OBJECT</div><h2>${id}</h2><p>${row.dataset.detail}</p><span class="pill info">${row.dataset.kind}</span>`}));
  $$('[data-observer-step]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-observer-step]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const out=$('[data-observer-detail]');if(out)out.textContent=btn.dataset.copy;if(btn.dataset.observerStep==='redacted'){$$('.redacted').forEach(r=>{r.classList.add('revealed');r.textContent=r.dataset.reveal||'redacted'})}}));
});
